config/routes.rb
Tamagotchi::Application.routes.draw do
  
  
  devise_for :users
  resources :users do
    resources :pets, only: [:index, :show]
  end

  resources :pets, except: [:index, :show]

  root 'pages#home'

end

app/models/pet.rb
class Pet < ActiveRecord::Base
	belongs_to :user

	RATING_MAX = 5
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
	has_one :pet
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def home
	end

end

app/controllers/pets_controller.rb
class PetsController < ApplicationController

  before_action :lookup_user, only: [:show]
  before_action :lookup_pet, only: [:show, :edit, :update, :destroy]


  def index
  end

  def create
    pet = current_user.create_pet(params.require(:pet).permit(:name, :bio))
    redirect_to user_pet_path(current_user, pet)
  end

  def new
    @pet = Pet.new
  end

  def edit
  end

  def show
    if @pet == nil
    redirect_to new_pet_path
    end
  end

  def update
    @pet.update_attributes(params.require(:pet).permit(:name, :bio, :rating))
    redirect_to user_pet_path(current_user, @pet)
  end

  def destroy
    @pet.destroy
    redirect_to user_url(current_user) 
  end

  private

  def lookup_user
    @user = User.find(params[:user_id])
  end

  def lookup_pet
    @pet = Pet.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all
  end

  def create
  end

  def new
  end

  def edit
  end

  def show
  	@user = User.find(params[:id])
  	@pet = @user.pet
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper

	def rating(r)
		result = ""

		r.times do
			result += content_tag("i", "", class: "fa fa-heart")
		end  
		
		(Pet::RATING_MAX - r).times do 
		  result += content_tag("i", "", class: "fa fa-heart-o")
		end
		result.html_safe 
	end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Tamagotchi</title>
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css">

<!-- Optional theme -->
	<link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->

  <link href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  </head>
<body>
	<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/users">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"> 
              <%= current_user.email %> <b class="caret"></b>
             </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <%= link_to "sign in", new_user_session_path %>   
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<div class="container"> 
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
	<%= yield %>
</div>
<%= javascript_include_tag "application" %>
<script src="http://netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>
</body>

</html>

app/views/pages/home.html.erb
<h1>WELCOME TO THE PET FANTASY WORLD</h1>

<%= link_to "Let me in", users_path %>

app/views/pets/_form.html.erb
<%= form_for @pet do |f| %>
  <div class= "form-group">
  <%= f.label :name %> :
  <br><%= f.text_field :name, class: "form-control" %>
  </div>
  <div class= "form-group">
  <%= f.label :bio %> :
  <br><%= f.text_area :bio, size: "60x12", class: "form-control" %>
  </div>
  <div class= "form-group">
  <%= f.label :rating %> :
  <br> <%= f.select :rating, (1..Pet::RATING_MAX), {}, class: "form-control" %>
  </div>
  <%= f.submit "Update", class: "btn btn-primary" %>
<% end %>

app/views/pets/edit.html.erb
<center><h1>Edit <%= current_user.email %> Tamagotchi's</h1></center>

<%= render 'form' %>

app/views/pets/index.html.erb
<h1>Pets#index</h1>
<p>Find me in app/views/pets/index.html.erb</p>

app/views/pets/new.html.erb
<h1>Nouveau Tamagotchi</h1>

<%= render "form" %>

app/views/pets/show.html.erb
<ul class="nav nav-tabs">
  <li> <%= link_to @pet.user.name, user_path(@pet.user) %></li>
  <li class="active"	> <%= link_to @pet.name, user_pet_path(@pet.user, @pet) %></li>
</ul>

<center><h1><i class="fa fa-bug"></i> <%= @pet.name %> - <%= @user.name %>'s Tamagotchi</h1></center>

<p><i class="fa fa-book"></i> <%= @pet.bio %></p>

<p><%= rating(@pet.rating) if !@pet.rating.nil? %> 
 </p>

<% if @pet.user == current_user %>
<p><%= link_to edit_pet_path(@pet), class: "btn btn-warning" do %>
	<i class="fa fa-pencil"></i> Edit
	<%end %>

  <%= link_to pet_path(@pet), method: :delete, data: { confirm: "Do you really want to delete this sweet little pet ?" }, class: "btn btn-danger" do %>
  <i class="fa fa-trash-o"></i> Delete
  <% end %>
</p>
<% end %>

app/views/users/index.html.erb
<h2>User list:</h2>

<ul>
	<% @users.each do |user| %>
		<li><%= link_to user.name, user_path(user) %></li>
	<% end %>
</ul>

app/views/users/show.html.erb
<ul class="nav nav-tabs">
  <li class="active"><a href="#">Infos</a></li>

 <% if @pet %>
  <li><%= link_to @pet.name, user_pet_path(@user, @pet) %></li>
  <% end %>
</ul>
<h2>Name : <%= @user.name %></h2>

<h2>Email : <%= @user.email %></h2>

<% unless @pet %>
  <%= link_to("Create a pet", new_pet_path, class: "btn btn-primary") if @user == current_user %>
<% end %>